### ISSUE TITLE
Fix Commit History

### ISSUE THREAD

**Issue by RudyBodo** [CellBIS/mojo-hakkefuin#5]
There are many bad historical commits in this project. 

### List of Problems :
- Many commit message doesn't sound like proper English.
- Many duplicate commits can be in one commit.
- Many commits that should be fixed in only one commit
- 104 commits must be deleted, then corrected according to the latest changes.

### To be solved :
- Delete all commits from 3e14daf to fb5a546
- Start a new commit according to what happened to start from commit 3e14daf to fb5a546

#### List of commits that can be deleted :
> fb5a546 - 10 days ago - `reformat structure`
5ccf2fa - 10 days ago - `remove "sudo: required"`
b6ebccf - 12 days ago - `move all backend tests to backend/lite/`
5d68f25 - 12 days ago - `use mariadb name`
f468495 - 12 days ago - `use semantic version for alpha and beta versions`
82b701e - 12 days ago - `change all keywords mysql to mariadb`
60579f5 - 12 days ago - `try travis-ci for postgresql`
4aadb88 - 12 days ago - `use build matrix only for older perl version`
6eb0d4b - 12 days ago - `use build matrix for older perl version`
7c18a29 - 12 days ago - `Remove duplicate Perl Modules`
986ba2c - 12 days ago - `remove duplicate perl modules`
915cde2 - 12 days ago - `try fix problem travis-ci from commit #272a37f`
272a37f - 12 days ago - `try fix problem travis-ci from commit #a49661b`
a49661b - 12 days ago - `try fix problem travis-ci from commit #5bf5edd`
5bf5edd - 12 days ago - `change mysql to mariadb for travis-ci testing`
eb10720 - 12 days ago - `add perl version for travis-ci testing`
a9497bb - 12 days ago - `fix error testing in travis-ci on command create database mysql`
e66f440 - 12 days ago - `fix example code in README.md`
ba10393 - 12 days ago - `change the version mechanism for the alpha and beta versions`
284965d - 7 months ago - `use config from "csrf.name" for CSRF Token in HTTP Header`
3478a88 - 7 months ago - `add EOF`
878cb34 - 7 months ago - `change scalar for time to scalar hashref. Fix typo of comment`
1027dc3 - 7 months ago - `fix typo in POD "Mojolicious::Plugin::Hakkefuin"`
0074d20 - 7 months ago - `update "Mojo::Hakkefuin::Backend" for EXPERIMENTAL Feature - EXPERIMENTAL Feature : "lock" and "unlock"`
b68f5c2 - 7 months ago - `update plugin file "Hakkefuin.pm" - POD and add EXPERIMENTAL Feature - EXPERIMENTAL Feature :   - Option "lock" and "cl.time"   - Add callback for "lock" and "unlock"   - Add Helper "lock" and "unlock"   - Add Subroutine "lock" and "unlock" - In POD:   - Changes all term "SimpleAuth" to "Hakkefuin"   - Update synopsis   - Add info for Option "csrf.name", "lock", "unlock", & "cl.time"   - Add info for Helper "mhf_lock" and "mhf_lock" - EXPERIMENTAL   - Update "year" in Copyright section.`
d676efb - 7 months ago - `update Mojo::Hakkefuin POD to change "SimpleAuth" to "Hakkefuin"`
b356542 - 7 months ago - `update Mojo::Hakkefuin::Sessions to add option cookie "samesite"`
12e46d4 - 7 months ago - `update "Changes" to change name module`
c1eca7f - 7 months ago - `update "Changes Log" for version 0.1-alpha and new version`
bcb765d - 7 months ago - `update plugin "Hakkefuin" file - fix typo param on sub "_sign_in"`
8ef05ed - 7 months ago - `revert basic module name to plugin module file`
9c2f827 - 7 months ago - `update .gitignore to exclude file *.tar.gz`
f110a4d - 7 months ago - `rename plugin file from "SimpleAuth" to "Hakkefuin"`
424b8a5 - 7 months ago - `update Makefile.PL to change base module name and version`
a45206a - 7 months ago - `change the module version file   from "Mojolicious::Plugin::SimpleAuth"     to "Mojo::Hakkefuin"`
2506231 - 7 months ago - `bump version 0.2`
72a02d7 - 7 months ago - `update Mojolicious::Plugin::SimpleAuth remove unused comment in POD`
108e325 - 7 months ago - `Update README.md remove unused comment`
22d2ce2 - 7 months ago - `Update README.md`
0a7fbbf - 7 months ago - `change all keywords "msa" to "mhf"`
b8261cc - 7 months ago - `Update Mojolicious::Plugin::SimpleAuth for change link repository`
99978f9 - 11 months ago - `update unit testing to test function for update auth - Backend MySQL/MariaDB`
0aae302 - 11 months ago - `update unit testing to test function for update auth - Backend Postgre`
2b56bca - 11 months ago - `update unit testing to test function for update auth`
5db5ae6 - 11 months ago - `fix bugs for auth update function.`
5b1945d - 11 months ago - `change all abbreviate "msa" to "mhf"`
2be079c - 11 months ago - `change all abbreviate "msa" to "mhf"`
bd9d5e2 - 11 months ago - `Testing auth update for cookies and csrf on backend sqlite`
25680ce - 11 months ago - `change all "msa" abbreviate to "mhf"`
e2fc83c - 11 months ago - `change all "msa" to "mhf"`
1a6c4d5 - 11 months ago - `change all "msa" abbreviate to "mhf"`
03da241 - 11 months ago - `Update cpanfile`
cab2334 - 11 months ago - `use "mhf_backend" on unit testing backend`
1f9ed6a - 11 months ago - `Change helper "msa_backend" to "mhf_backend"`
fdc62d1 - 11 months ago - `Update cpanfile dan Makefile.PL`
83bc111 - 11 months ago - `Change default table_name from "mojo_simple_auth" to "mojo_hakkefuin"`
8b46db7 - 11 months ago - `change attribute "mojo_msa" to "mojo_hf"`
ddab632 - 1 year, 2 months ago - `Rename default cookie_name from "_msa" to "_hakkefuin"`
b765bf2 - 1 year, 3 months ago - `Fix typo in hook "after_build_tx"`
2cde8ee - 1 year, 3 months ago - `Fix typo on attribute "utils"`
37210e1 - 1 year, 3 months ago - `fix bug on plugin file module.`
89a01a1 - 1 year, 3 months ago - `Rename all module name to "Hakkefuin"`
6b01d21 - 1 year, 3 months ago - `Update README.md - Module name`
01754af - 1 year, 4 months ago - `remove script for debug`
c091354 - 1 year, 4 months ago - `update skip test if env TEST_ONLINE_pg is unset.`
5db161a - 1 year, 4 months ago - `update skip test if env TEST_ONLINE_mysql is unset.`
46ffb38 - 1 year, 4 months ago - `Update cpanfile to remove DBD::*`
5967df3 - 1 year, 4 months ago - `Update .travis.yml for enable testing postgres as backend`
1c7a122 - 1 year, 4 months ago - `Update .travis.yml for enable testing postgres as backend`
34de3a4 - 1 year, 4 months ago - `Add PostgreSQL as additional backend`
9d21f79 - 1 year, 4 months ago - `Remove duplicate initialization CellBIS::SQL::Abstract`
9b7c154 - 1 year, 4 months ago - `remove unused comment`
82f135f - 1 year, 4 months ago - `Update .travis.yml to enable "mysql" backend testing`
3d171ce - 1 year, 4 months ago - `fix .travis.yml`
f63228a - 1 year, 4 months ago - `Try travis-ci and update cpanfile for remove mysql`
bd5d39d - 1 year, 4 months ago - `Try travis-ci`
46ccfaf - 1 year, 4 months ago - `Try travis-ci`
e060605 - 1 year, 4 months ago - `Try travis-ci`
7e5814b - 1 year, 4 months ago - `Try travis-ci`
3801091 - 1 year, 4 months ago - `Try travis-ci`
a66f4ad - 1 year, 4 months ago - `Try travis-ci and update cpanfile`
c08fdcc - 1 year, 4 months ago - `Try travis-ci`
8a5a5d2 - 1 year, 4 months ago - `Try travis-ci`
98e6723 - 1 year, 4 months ago - `Try travis-ci`
b450c95 - 1 year, 4 months ago - `Try travis-ci`
5e7c92a - 1 year, 4 months ago - `Try travis-ci`
a259ef2 - 1 year, 4 months ago - `Try travis-ci`
ff6950b - 1 year, 4 months ago - `Try travis-ci`
42f29a5 - 1 year, 4 months ago - `Try travis-ci`
834c5e8 - 1 year, 4 months ago - `Try travis-ci`
e94f165 - 1 year, 4 months ago - `Try travis-ci`
28cb7c2 - 1 year, 4 months ago - `Try travis-ci`
a62f0bb - 1 year, 4 months ago - `Try travis-ci`
d707f6d - 1 year, 4 months ago - `Try travis-ci`
b42d56a - 1 year, 4 months ago - `Try travis-ci`
9b4d77b - 1 year, 4 months ago - `try travis-ci`
4e61646 - 1 year, 4 months ago - `update cpanfile for feature deps "mysql"`
aad5e45 - 1 year, 4 months ago - `Install deps with command "cpanm -n --installdeps --with-feature=mysql"`
1853656 - 1 year, 4 months ago - `use "cpan -i" when install DBD::mysql and Mojo::mysql`
f7cd937 - 1 year, 4 months ago - `fix command to install "DBD::mysql and Mojo::mysql"`
0d81697 - 1 year, 4 months ago - `add command to install "DBD::mysql"`
a8edf29 - 1 year, 4 months ago - `add command to install "Mojo::mysql"`
2f3805b - 1 year, 4 months ago - `fix mysql url`
3e14daf - 1 year, 4 months ago - `Update .travis.yml to enable "mysql" backend testing`

**Comment by yusrideb** [comment]
Thanks for open this issue. I've made a fork for this project at [CellBISOld Project](https://github.com/CellBISold/mojo-hakkefuin).

**Comment by yusrideb** [comment]
After reviewing the commit list, found 4 more that need to be deleted.

### Additions that need to be deleted :
> 4f6c681 - 1 year, 4 months ago - `Enable backend "mysql"`
7f685b4 - 1 year, 4 months ago - `Update Mojo::SimpleAuth - add attributes "dsn and migration" - update params for backend`
8cc8be0 - 1 year, 4 months ago - `Update backend "sqlite"  to implement method "empty_table and drop_table" from base class`
77ad91a - 1 year, 4 months ago - `Update Mojo::SimpleAuth::Backend - change default name field table "lock" to "lock_state" - add method for "drop and empty" table - add attribute 'dsn' - remove attribute 'app'`

### TO DO : 
Start from commit 77ad91a to fb5a546 will be deleted. Total 108 commit's.

**Comment by yusrideb** [comment]
This issue have Done. Closed with beta release - v0.1.1-beta
:+1:
