### ISSUE TITLE
Fix POD coverage in all modules

### ISSUE THREAD

**Issue by CellBIS** [CellBIS/mojo-hakkefuin#9]
List of modules that have POD coverage issues :
- Mojo::Hakkefuin
- Mojo::Hakkefuin::Sessions
- Mojo::Hakkefuin::Backend

List of modules that don't have POD : 
- Mojo::Hakkefuin::Backend::sqlite
- Mojo::Hakkefuin::Backend::mariadb
- Mojo::Hakkefuin::Backend::pg

**Comment by yusrideb** [comment]
this issue has been done
